# Setup
title:               Kurtosis.fit
tagline:             'Intensity over Consistency'
description:         'Intensity over Consistency'
url:                 https://kurtosis.fit
baseurl:             'https://kurtosis.fit/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Akash Patro
  url:               https://twitter.com/aptro_

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
